/**
 * @file tkl_otp_flash.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "tkl_otp_flash.h"
#include "tuya_cloud_types.h"
#include "tuya_error_code.h"
#include "flash_bypass.h"
#include "tkl_ipc.h"
#include "tkl_memory.h"

#define OTP_FLASH_SIZE 1024

#define OTP_FLASH_RF_ADDR 0
#define OTP_FLASH_RF_SIZE 512

#define OTP_FLASH_OPENSDK_ADDR (OTP_FLASH_RF_ADDR + OTP_FLASH_RF_SIZE)
#define OTP_FLASH_OPENSDK_SIZE 256

static int __otp_flash_get_addr(uint8_t type)
{
    switch (type) {
    case OTP_FLASH_TYPE_RF: // rf
        return OTP_FLASH_RF_ADDR;

    case OTP_FLASH_TYPE_OPENSDK: // opensdk
        return OTP_FLASH_OPENSDK_ADDR;

    default:
        bk_printf("invalid type: %d\n", type);
        return -1;
    }

    return -1;
}

/**
 * @brief read otp flash
 *
 * @param[in] type: data type
 * @param[out] dst: pointer of buffer
 * @param[in] size: size of buffer
 *
 * @note This API is used for reading flash.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_otp_flash_read(uint8_t type, uint8_t *dst, uint32_t size)
{
    // --- BEGIN: user implements ---
    int ret = 0;
    if ((dst == NULL) || (size > OTP_FLASH_SIZE) || (size == 0))
        return OPRT_INVALID_PARM;

    int addr = __otp_flash_get_addr(type);
    if (addr < 0)
        return OPRT_INVALID_PARM;

    flash_bypass_otp_ctrl_t otp_op = {0};
    otp_op.otp_idx = 1; // "1 or 2 or 3"
    otp_op.addr_offset = addr;
    otp_op.write_len = 0;
    otp_op.write_buf = NULL;
    otp_op.read_len = size;
    otp_op.read_buf = dst;

    ret = flash_bypass_otp_operation(FLASH_BYPASS_OTP_READ, &otp_op);
    if (ret != BK_OK) {
        return OPRT_OS_ADAPTER_FLASH_READ_FAILED;
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief write otp flash
 *
 * @param[in] type: data type
 * @param[in] src: pointer of buffer
 * @param[in] size: size of buffer
 *
 * @note This API is used for writing flash.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_otp_flash_write(uint8_t type, const uint8_t *src, uint32_t size)
{
    // --- BEGIN: user implements ---
    int ret = 0;
    flash_bypass_otp_ctrl_t otp_op = {0};

    if ((src == NULL) || (size > OTP_FLASH_SIZE) || (size == 0))
        return OPRT_INVALID_PARM;

    int addr = __otp_flash_get_addr(type);
    if (addr < 0)
        return OPRT_INVALID_PARM;

    otp_op.otp_idx = 1; // "1 or 2 or 3"
    otp_op.addr_offset = addr;
    otp_op.write_len = size;
    otp_op.write_buf = src;
    otp_op.read_len = 0;
    otp_op.read_buf = NULL;

    ret = flash_bypass_otp_operation(FLASH_BYPASS_OTP_WRITE, &otp_op);
    if (ret != BK_OK) {
        return OPRT_OS_ADAPTER_FLASH_WRITE_FAILED;
    }
    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief erase otp flash
 *
 * @param[in] type: data type
 * @param[in] size: size of flash block
 *
 * @note This API is used for erasing flash.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_otp_flash_erase(uint8_t type, uint32_t size)
{
    // --- BEGIN: user implements ---
    int ret = 0;
    if ((size > OTP_FLASH_SIZE) || (size == 0))
        return OPRT_INVALID_PARM;

    int addr = __otp_flash_get_addr(type);
    if (addr < 0)
        return OPRT_INVALID_PARM;

    flash_bypass_otp_ctrl_t otp_op = {0};
    otp_op.otp_idx = 1; // "1 or 2 or 3"
    otp_op.addr_offset = addr;
    otp_op.write_len = size;
    otp_op.write_buf = NULL;
    otp_op.read_len = 0;
    otp_op.read_buf = NULL;

    ret = flash_bypass_otp_operation(FLASH_BYPASS_OTP_EARSE, &otp_op);
    if (ret != BK_OK) {
        return OPRT_OS_ADAPTER_FLASH_ERASE_FAILED;
    }
    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief lock otp flash
 *
 * @param[in] none
 *
 * @note This API is used for erasing flash.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_otp_flash_lock(void)
{
    // --- BEGIN: user implements ---
    int ret = 0;
    int rfcali_backup_rslt = 0;
    extern int backup_rfcali_data(void);
    // backup rf calibration data
    rfcali_backup_rslt = backup_rfcali_data();
    if (rfcali_backup_rslt != 0) {
        bk_printf("backup rfcali data failed\n");
        return OPRT_COM_ERROR;
    }

    flash_bypass_otp_ctrl_t otp_op = {0};
    otp_op.otp_idx = 1; // "1 or 2 or 3"
    otp_op.addr_offset = 0;
    otp_op.write_len = 0;
    otp_op.write_buf = NULL;
    otp_op.read_len = 0;
    otp_op.read_buf = NULL;

    // TODO: debug
    // ret = flash_bypass_otp_operation(FLASH_BYPASS_OTP_LOCK, &otp_op);
    if (ret != BK_OK){
        bk_printf("lock otp flash failed\n");
        return OPRT_COM_ERROR;
    }

    bk_printf("lock otp flash success\r\n");

    return OPRT_OK;
    // --- END: user implements ---
}

/*
 * @brief check if otp flash is locked
 *
 * @param[in] is_locked: pointer of lock status
 *
 * @note This API is used for checking the lock status of otp flash.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_otp_flash_is_locked(uint8_t *is_locked)
{
    if (NULL == is_locked) {
        return OPRT_INVALID_PARM;
    }
    *is_locked = 0;

    uint8_t *res_buf = tkl_system_malloc(sizeof(uint16_t));
    if (NULL == res_buf){
        return OPRT_MALLOC_FAILED;
    }
    memset(res_buf, 0, sizeof(uint16_t));

    struct ipc_msg_s msg = {0};
    msg.type = TKL_IPC_TYPE_SYS;
    msg.subtype = TKL_IPC_TYPE_SYS_OTP_REG_GET;
    msg.res_param = res_buf;
    msg.res_len = sizeof(uint16_t);

    tuya_ipc_send_sync(&msg);

    uint16_t *p_sts_val = msg.res_param;
    bk_printf("ap sts_val : 0x%x\r\n", *p_sts_val);

    if (*p_sts_val == 0xa38) {
        *is_locked = 1;
    } else {
        *is_locked = 0;
    }

    tkl_system_free(res_buf);
    res_buf = NULL;

    return 0;
}
