// Copyright 2020-2021 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#ifdef __cplusplus
extern "C" {
#endif


#define GPIO_DEFAULT_DEV_CONFIG  \
{\
	{GPIO_0,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, GPIO_INPUT_ENABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_1,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, GPIO_INPUT_ENABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_2,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_INVALID, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_3,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_INVALID, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_4,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_INVALID, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_6,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_7,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_I2S1_SYNC, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_14, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SDIO_HOST_CLK, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_15, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SDIO_HOST_CMD, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_16, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SDIO_HOST_DATA0, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_17, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SDIO_HOST_DATA1, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_18, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SDIO_HOST_DATA2, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_19, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SDIO_HOST_DATA3, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_20, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_21, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, GPIO_INPUT_ENABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_22, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_23, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_24, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_25, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_26, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, GPIO_INPUT_ENABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_27, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_40, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_41, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_42, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
	{GPIO_43, GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1,GPIO_INIT_ENABLE,GPIO_TIME_SHARING_MULTIPLEX_ENABLE},\
}


#ifdef __cplusplus
}
#endif
